// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm21HCsgx3qHvHEnRmAcMiBiIZrqzummI',
    appId: '1:53788052394:web:ed3a6f9efa3663aa51f9d3',
    messagingSenderId: '53788052394',
    projectId: 'trustme-11',
    authDomain: 'trustme-11.firebaseapp.com',
    storageBucket: 'trustme-11.firebasestorage.app',
    measurementId: 'G-YY6LRCJB96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8s7nnEyIp_DZcI27wahxlHFKjo5EZTSc',
    appId: '1:53788052394:android:84a01b2b8f9a058b51f9d3',
    messagingSenderId: '53788052394',
    projectId: 'trustme-11',
    storageBucket: 'trustme-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8GrMNhA0tpUmehvhSdGpluKsuIfJR29g',
    appId: '1:53788052394:ios:99ee2282561af24d51f9d3',
    messagingSenderId: '53788052394',
    projectId: 'trustme-11',
    storageBucket: 'trustme-11.firebasestorage.app',
    iosBundleId: 'com.xmechat.dev.xmechat',
  );
}
